---
.catalog:
  name: "pgbouncer"
  version: "v1.7.2-3"
  description: "Pgbouncer Stack"
  uuid: pgbouncer-2
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "USERLIST"
      label: "userlist.txt"
      description: "Content of userlist.txt"
      type: "multiline"
      required: true
    - variable: "PG_HBA"
      label: "pg_hba.conf"
      description: "Content of pg_hba.conf"
      type: "multiline"
      required: true
    - variable: "DB_MAPPING"
      label: "Db Mapping"
      description: "Mapping between db name and hosts"
      type: "multiline"
      required: true
      default: |
        "* = host=db"
    - variable: "TARGET_HOST"
      label: "Target host"
      description: "Target Postgresql database"
      type: "service"
      default: "postgres-cluster/lb"
      required: true
    - variable: "LISTEN_PORT"
      label: "Listen Port"
      description: "Listen Port for Pgbouncer"
      default: "5432"
      required: true
    - variable: "CERTIFICATE_DESCRIPTION"
      label: "Certificate description"
      description: "String used to generate server certificate"
      type: "string"
      default: "/C=FR/O=camptocamp"
      required: true

pgbouncer:
  scale: 1
  health_check:
    port: 6432
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
