---
.catalog:
  name: "pgbouncer"
  version: "v1.7.2-1"
  description: "Pgbouncer Stack"
  uuid: pgbouncer-0
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "USERLIST"
      label: "userlist.txt"
      description: "Content of userlist.txt"
      type: "multiline"
      required: true
    - variable: "PG_HBA"
      label: "pg_hba.conf"
      description: "Content of pg_hba.conf"
      type: "multiline"
      required: true
    - variable: "TARGET_HOST"
      label: "Target host"
      description: "Target Postgresql database"
      type: "service"
      default: "lb.postgres-cluster"
      required: true
    - variable: "LISTEN_PORT"
      label: "Listen Port"
      description: "Listen Port for Pgbouncer"
      default: "5432"
      required: true

pgbouncer:
  scale: 1
  health_check:
    port: 6432
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
